### ISSUE TITLE
docsforge docs

### ISSUE THREAD

**Issue by erez-o** [gennaroprota/breath#2]
Hi, 

I've noticed you uploaded your project to docsforge. Thanks for liking it :)

Do you want any help with configuring the it better?

I did notice a couple of odd behaviors in the generated docs. 
Doxygen detects various "nameless user defined groups", for example [here](https://breath.docsforge.com/master/api/breath/performance_counter_policy/).  
Maybe you can explain a bit what you wanted to do?

You can use groups in docsforge, but I didn't expect nameless groups to have a purpose, look at https://help.docsforge.com/master/autodoc-settings/#sort_by_group for an example output.

Good day.

**Comment by gennaroprota** [comment]
As explained in private email to Erez (I'm reporting it here for future readers of the issue), the goal was to use the same piece of documentation for all members of the group. This is done with the `DISTRIBUTE_GROUP_DOC` option in Doxygen. DocsForge didn't support it at the time the issue was open, but Erez kindly added it (thanks :-)).

Unless we want to add more to this issue, I'm going to close it in a couple of days.

**Comment by gennaroprota** [comment]
Thanks, Erez. I'm closing this, now.
